pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh """
                  cd Chapter08/sample1
                  chmod +x gradlew
                  ./gradlew build
                """
            }
        }

        stage('Run in Master Branch') {
            when {
                branch "master"
            }
            steps {
                sh """
                   cd Chapter08/sample1
                   ./gradlew jacocoTestCoverageVerification
                """   
            }
        }

        stage('Run all other Tests') {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew test
                  ./gradlew jacocoTestReport
                """
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failure'
        }
        success {
            echo 'Pipeline ran perfectly'
        }
    }
}
