pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh """
                  cd Chapter08/sample1
                  ls -l
                  chmod +x gradlew
                  ./gradlew build
                """
            }
        }

        stage('Check Java Changes') {
            when {
                changeset "**/*.java"
            }
            steps {
                sh """
                   cd Chapter08/sample1
                   ./gradlew codecoverage
                   ./gradlew checkstyle
                """   
            }
        }

        stage('Run all other Tests') {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew jacocoTestReport
                  ./gradlew jacocoTestCoverageVerification
                """
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failure'
        }
        success {
            echo 'Pipeline ran perfectly'
        }
    }
}
